var milestones = [
   {
      "url": "https://api.github.com/repos/biorender/biorender/milestones/1",
      "html_url": "https://github.com/biorender/biorender/milestones/Mitochondrion%20Scene",
      "labels_url": "https://api.github.com/repos/biorender/biorender/milestones/1/labels",
      "id": 1563953,
      "number": 1,
      "title": "Mitochondrion Scene",
      "description": "",
      "creator": {
         "login": "thejmazz",
         "id": 1270998,
         "avatar_url": "https://avatars.githubusercontent.com/u/1270998?v=3",
         "gravatar_id": "",
         "url": "https://api.github.com/users/thejmazz",
         "html_url": "https://github.com/thejmazz",
         "followers_url": "https://api.github.com/users/thejmazz/followers",
         "following_url": "https://api.github.com/users/thejmazz/following{/other_user}",
         "gists_url": "https://api.github.com/users/thejmazz/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/thejmazz/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/thejmazz/subscriptions",
         "organizations_url": "https://api.github.com/users/thejmazz/orgs",
         "repos_url": "https://api.github.com/users/thejmazz/repos",
         "events_url": "https://api.github.com/users/thejmazz/events{/privacy}",
         "received_events_url": "https://api.github.com/users/thejmazz/received_events",
         "type": "User",
         "site_admin": false
      },
      "open_issues": 4,
      "closed_issues": 0,
      "state": "open",
      "created_at": "2016-02-04T18:14:57Z",
      "updated_at": "2016-02-09T05:32:44Z",
      "due_on": "2016-02-22T05:00:00Z",
      "closed_at": null
   },
   {
      "url": "https://api.github.com/repos/biorender/biorender/milestones/4",
      "html_url": "https://github.com/biorender/biorender/milestones/Graphics/Modellng%20Backbone",
      "labels_url": "https://api.github.com/repos/biorender/biorender/milestones/4/labels",
      "id": 1571945,
      "number": 4,
      "title": "Graphics/Modellng Backbone",
      "description": "",
      "creator": {
         "login": "thejmazz",
         "id": 1270998,
         "avatar_url": "https://avatars.githubusercontent.com/u/1270998?v=3",
         "gravatar_id": "",
         "url": "https://api.github.com/users/thejmazz",
         "html_url": "https://github.com/thejmazz",
         "followers_url": "https://api.github.com/users/thejmazz/followers",
         "following_url": "https://api.github.com/users/thejmazz/following{/other_user}",
         "gists_url": "https://api.github.com/users/thejmazz/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/thejmazz/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/thejmazz/subscriptions",
         "organizations_url": "https://api.github.com/users/thejmazz/orgs",
         "repos_url": "https://api.github.com/users/thejmazz/repos",
         "events_url": "https://api.github.com/users/thejmazz/events{/privacy}",
         "received_events_url": "https://api.github.com/users/thejmazz/received_events",
         "type": "User",
         "site_admin": false
      },
      "open_issues": 7,
      "closed_issues": 0,
      "state": "open",
      "created_at": "2016-02-09T04:40:30Z",
      "updated_at": "2016-02-09T05:39:19Z",
      "due_on": "2016-03-15T04:00:00Z",
      "closed_at": null
   },
   {
      "url": "https://api.github.com/repos/biorender/biorender/milestones/6",
      "html_url": "https://github.com/biorender/biorender/milestones/Basic%20Cell%20Scene",
      "labels_url": "https://api.github.com/repos/biorender/biorender/milestones/6/labels",
      "id": 1571948,
      "number": 6,
      "title": "Basic Cell Scene",
      "description": "",
      "creator": {
         "login": "thejmazz",
         "id": 1270998,
         "avatar_url": "https://avatars.githubusercontent.com/u/1270998?v=3",
         "gravatar_id": "",
         "url": "https://api.github.com/users/thejmazz",
         "html_url": "https://github.com/thejmazz",
         "followers_url": "https://api.github.com/users/thejmazz/followers",
         "following_url": "https://api.github.com/users/thejmazz/following{/other_user}",
         "gists_url": "https://api.github.com/users/thejmazz/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/thejmazz/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/thejmazz/subscriptions",
         "organizations_url": "https://api.github.com/users/thejmazz/orgs",
         "repos_url": "https://api.github.com/users/thejmazz/repos",
         "events_url": "https://api.github.com/users/thejmazz/events{/privacy}",
         "received_events_url": "https://api.github.com/users/thejmazz/received_events",
         "type": "User",
         "site_admin": false
      },
      "open_issues": 8,
      "closed_issues": 0,
      "state": "open",
      "created_at": "2016-02-09T04:41:41Z",
      "updated_at": "2016-02-09T05:40:23Z",
      "due_on": "2016-04-15T04:00:00Z",
      "closed_at": null
   },
   {
      "url": "https://api.github.com/repos/biorender/biorender/milestones/2",
      "html_url": "https://github.com/biorender/biorender/milestones/Final",
      "labels_url": "https://api.github.com/repos/biorender/biorender/milestones/2/labels",
      "id": 1571930,
      "number": 2,
      "title": "Final",
      "description": "",
      "creator": {
         "login": "thejmazz",
         "id": 1270998,
         "avatar_url": "https://avatars.githubusercontent.com/u/1270998?v=3",
         "gravatar_id": "",
         "url": "https://api.github.com/users/thejmazz",
         "html_url": "https://github.com/thejmazz",
         "followers_url": "https://api.github.com/users/thejmazz/followers",
         "following_url": "https://api.github.com/users/thejmazz/following{/other_user}",
         "gists_url": "https://api.github.com/users/thejmazz/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/thejmazz/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/thejmazz/subscriptions",
         "organizations_url": "https://api.github.com/users/thejmazz/orgs",
         "repos_url": "https://api.github.com/users/thejmazz/repos",
         "events_url": "https://api.github.com/users/thejmazz/events{/privacy}",
         "received_events_url": "https://api.github.com/users/thejmazz/received_events",
         "type": "User",
         "site_admin": false
      },
      "open_issues": 2,
      "closed_issues": 0,
      "state": "open",
      "created_at": "2016-02-09T04:23:36Z",
      "updated_at": "2016-02-09T05:41:18Z",
      "due_on": "2016-04-29T04:00:00Z",
      "closed_at": null
   }
];
var status = "refreshing";